global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'spiralos'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 'spiralos_exporter'
    static_configs:
      - targets: ['localhost:8001']